/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.produto;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Flavio
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuSalvarSerializado = new javax.swing.JMenuItem();
        menuSalvarTexto = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuForenecedor = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu2.setText("Salvar");

        menuSalvarSerializado.setText("Salvar em Serialização");
        jMenu2.add(menuSalvarSerializado);

        menuSalvarTexto.setText("Salvar em Texto");
        jMenu2.add(menuSalvarTexto);

        menuSair.setText("Sair");
        jMenu2.add(menuSair);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Gerenciamento");

        menuProduto.setText("Produto");
        jMenu1.add(menuProduto);

        menuCliente.setText("Cliente");
        jMenu1.add(menuCliente);

        menuForenecedor.setText("Fornecedor");
        jMenu1.add(menuForenecedor);

        menuFuncionario.setText("Funcionário");
        jMenu1.add(menuFuncionario);

        menuCompra.setText("Compra");
        jMenu1.add(menuCompra);

        menuVenda.setText("Venda");
        jMenu1.add(menuVenda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMenuSair() {
        return menuSair;
    }

    public void setMenuSair(JMenuItem menuSair) {
        this.menuSair = menuSair;
    }

    public JMenuItem getMenuSalvarSerializacao() {
        return menuSalvarSerializado;
    }

    public void setMenuSalvarSerializacao(JMenuItem menuSalvarPersistence) {
        this.menuSalvarSerializado = menuSalvarPersistence;
    }

    public JMenuItem getMenuSalvarTexto() {
        return menuSalvarTexto;
    }

    public void setMenuSalvarTexto(JMenuItem menuSalvarTexto) {
        this.menuSalvarTexto = menuSalvarTexto;
    }
    
    public JMenuItem getMenuFuncionario() {
        return menuFuncionario;
    }

    public void setMenuFuncionario(JMenuItem menuFuncionario) {
        this.menuFuncionario = menuFuncionario;
    }

    
    
    public JMenuItem getMenuForenecedor() {
        return menuForenecedor;
    }

    public void setMenuForenecedor(JMenuItem menuForenecedor) {
        this.menuForenecedor = menuForenecedor;
    }
    
    public JDesktopPane getjDesktopPane1() {
        return painelPrincipal;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.painelPrincipal = jDesktopPane1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JDesktopPane getPainelPrincipal() {
        return painelPrincipal;
    }

    public void setPainelPrincipal(JDesktopPane painelPrincipal) {
        this.painelPrincipal = painelPrincipal;
    }

    
    
    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getMenuCliente() {
        return menuCliente;
    }

    public void setMenuCliente(JMenuItem menuCliente) {
        this.menuCliente = menuCliente;
    }

    public JMenuItem getMenuCompra() {
        return menuCompra;
    }

    public void setMenuCompra(JMenuItem menuCompra) {
        this.menuCompra = menuCompra;
    }

    public JMenuItem getMenuProduto() {
        return menuProduto;
    }

    public void setMenuProduto(JMenuItem menuProduto) {
        this.menuProduto = menuProduto;
    }

    public JMenuItem getMenuVenda() {
        return menuVenda;
    }

    public void setMenuVenda(JMenuItem menuVenda) {
        this.menuVenda = menuVenda;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuForenecedor;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSalvarSerializado;
    private javax.swing.JMenuItem menuSalvarTexto;
    private javax.swing.JMenuItem menuVenda;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
