/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.produto;

import javax.swing.JButton;

/**
 *
 * @author Flavio
 */
public class ViewModoRecuperarDado extends javax.swing.JFrame {

    /**
     * Creates new form ViewModoRecuperarDado
     */
    public ViewModoRecuperarDado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSerializacao = new javax.swing.JButton();
        btnTexto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSerializacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSerializacao.setText("Recuperar os dados da serialização");

        btnTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTexto.setText("Recuperar os dados do arquivo texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnSerializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnSerializacao() {
        return btnSerializacao;
    }

    public void setBtnSerializacao(JButton btnSerializacao) {
        this.btnSerializacao = btnSerializacao;
    }

    public JButton getBtnTexto() {
        return btnTexto;
    }

    public void setBtnTexto(JButton btnTexto) {
        this.btnTexto = btnTexto;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSerializacao;
    private javax.swing.JButton btnTexto;
    // End of variables declaration//GEN-END:variables
}
